/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GraphIndexRouteImport } from './routes/graph.index'
import { Route as BoardIndexRouteImport } from './routes/board.index'
import { Route as BoardNewRouteImport } from './routes/board.new'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphIndexRoute = GraphIndexRouteImport.update({
  id: '/graph/',
  path: '/graph/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardIndexRoute = BoardIndexRouteImport.update({
  id: '/board/',
  path: '/board/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardNewRoute = BoardNewRouteImport.update({
  id: '/board/new',
  path: '/board/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/board/new': typeof BoardNewRoute
  '/board': typeof BoardIndexRoute
  '/graph': typeof GraphIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/board/new': typeof BoardNewRoute
  '/board': typeof BoardIndexRoute
  '/graph': typeof GraphIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/board/new': typeof BoardNewRoute
  '/board/': typeof BoardIndexRoute
  '/graph/': typeof GraphIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/board/new' | '/board' | '/graph'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/board/new' | '/board' | '/graph'
  id: '__root__' | '/' | '/login' | '/board/new' | '/board/' | '/graph/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  BoardNewRoute: typeof BoardNewRoute
  BoardIndexRoute: typeof BoardIndexRoute
  GraphIndexRoute: typeof GraphIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph/': {
      id: '/graph/'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/': {
      id: '/board/'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/new': {
      id: '/board/new'
      path: '/board/new'
      fullPath: '/board/new'
      preLoaderRoute: typeof BoardNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  BoardNewRoute: BoardNewRoute,
  BoardIndexRoute: BoardIndexRoute,
  GraphIndexRoute: GraphIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
